### ISSUE TITLE
Stanford3dDataset_v1.2_Aligned_Version seems not so aligned

### ISSUE THREAD

**Issue by aborovac** [charlesq34/pointnet#20]
![stanford3ddataset_v1 2_aligned_version_area6](https://user-images.githubusercontent.com/15086478/27793745-94211d80-5fff-11e7-8a75-d8f689805153.png)

As you can see in the screenshot, hallways and rooms on the right side  seem misaligned.

This is visualization of Area6 .txt pointclouds from Stanford3dDataset_v1.2_Aligned_Version dataset.

**Comment by charlesq34** [comment]
Hi @aborovac 

Could you point where it is misaligned?

actually the data is processed by other PhD students in Prof. Saverese's lab:
http://cvgl.stanford.edu/index.html

**Comment by aborovac** [comment]
To fix misalignment I applied different rotations to some of the pointclouds. Below is the list of pointclouds and corresponding degrees to be applied (rotate around center point of point cloud)
Area6:
  ["office_11"]=90
  ["office_12"]=180
  ["office_13"]=180
  ["office_15"]=180
  ["office_16"]=180
  ["office_19"]=180
  ["office_22"]=180
  ["office_23"]=180
  ["office_24"]=180
  ["office_25"]=180
  ["office_26"]=180
  ["office_27"]=180
  ["office_28"]=180
  ["office_29"]=180
  ["office_31"]=90
  ["office_30"]=180
  ["office_33"]=180
  ["office_34"]=180
  ["office_35"]=180
  ["office_36"]=180
  ["office_37"]=180
  ["pantry_1"]=180
  ["hallway_1"]=-90
  ["hallway_2"]=90


![stanford3ddataset_v1 2_aligned_version_area6_aligned](https://user-images.githubusercontent.com/15086478/27906470-ef85d8d2-6243-11e7-9908-61a3c02fcff3.png)

**Comment by Logrus** [comment]
There are two versions of the dataset: Original and aligned.
Aligned refers to the version where all of the rooms are rotated to be aligned with the canonical coordinate system.
Here what official readme says:
> For those who want to use the globally aligned* point cloud versions directly, there exists a folder named "Aligned_Version", which contains the exact data as above (original version), but rotated according to the global alignment angles provided. Please note that the aligned version is only rotated; neither translated nor normalized. 
> ...
> *aligned = corresponds to the alignment that takes place before the element parsing (see in paper Section 3.2. Canonical Coordinate System Among Spaces)

So instead of rotating Aligned version you could just download the original dataset, which is what you show in the picture by default.

Here you can fill out the official form and have access to the both versions and the documentation:
https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1

The access to the dataset is instant once you have submitted the form.
