### ISSUE TITLE
what's the difference without RGB in experiment of Semantic Segmentation

### ISSUE THREAD

**Issue by joyousrabbit** [charlesq34/pointnet#30]
Hello, great work, very impressive, should be best paper in CVPR2017.

What's the accuracy drop with and without RGB in experiment of Semantic Segmentation?

Btw, don't you think to concatenate the Max with a Min? in order to save half parameters.

**Comment by charlesq34** [comment]
Hi @joyousrabbit I currently don't have specific numbers at hand. yet by referring to the original dataset paper there could be a ~4% accuracy drop if we don't use color.

I'm not sure how much max+min could help since we already have ReLU which makes everything positive. I remember at some point I have tried max+min for pooling but didn't see any significant difference in performance.

**Comment by nassarofficial** [comment]
@joyousrabbit how can I train without RGB, which files should I edit, because I am struggling with my own dataset to convert it to h5 and then train.... Do you have a fork?

**Comment by nassarofficial** [comment]
Thank you so much!
