### ISSUE TITLE
Questions about ModelNet40 point clouds data

### ISSUE THREAD

**Issue by godspeed1989** [charlesq34/pointnet#42]
Excellent work! Thank you very much.

I have two questions about the point clouds data you provide: 

(1) How could you generate `fixed size(1024,2^10)` point cloud from mesh file?
      I try to use ray casting to generate, but it does not produce num of points equal to power of 2

(2) For each point could, I notice the first half part(0-1023) and the second half part(1024-2047) are identical
      Does it still meaningful to train pointnet with 2048 as `num_point` ?

**Comment by daerduoCarey** [comment]
(1) We use furthest point sampling algorithm to sample likely uniform point cloud from mesh. The number of points in point cloud does not have to be power of 2. This is just to make the implementation easy.
(2) Where do you find the two parts of points are identical? This is weird. We should have sampled 2048 at the very beginning and order them so that the first 1024 points can still form a valid point cloud. The rest 1024-2047 points are different points but adding more details in the first 0-1023 points. Again, we use furthest point sampling, so that the first k points (point 0~k out of 2048) can always form a likely uniform and complete point cloud to approximate the shape.

Hope my answer helps.

Bests,
Kaichun

**Comment by godspeed1989** [comment]
It is my fault
I wrongly dumped the points, sorry to bother you

Could you provide any details about implementing farthest point sampling algorithm?
I use [CGAL](https://doc.cgal.org/latest/AABB_tree/index.html#Chapter_3D_Fast_Intersection_and_Distance_Computation) to implement ray casting for point cloud generation, but it is too slow....

**Comment by daerduoCarey** [comment]
You can just uniformly and randomly sample 4096 points using heuristic algorithms, e.g. select a random surface first according to the surface area, and then randomly sample a point on that triangle in barycentric coordinate. Then, you can run a for loop, each time selecting a new point from the sampled 4096 points that is furthest to all the selected points. 

Hope this help.

Bests,
Kaichun

**Comment by godspeed1989** [comment]
barycentric coordinate !
That really help and inspire me a lot.
Thank you.

There is one thing I still don't know:
How to select (or measure) the new point which should be `furthest` to all the selected points?

**Comment by EndingCredits** [comment]
The way I did this was to use the [PCL](http://pointclouds.org/) `pcl_mesh_sampling`. I believe this works by flattening the mesh and then randomly sampling on the triangles according to area. There is also a utility to sample according to polar co-ordinates and projections in the PCL library utilities.

It might be good to standardise the test set (and also train set) for ModelNet40 with point clouds as I know at least one [other paper](https://arxiv.org/abs/1611.04500) which has done the same thing. In particular, I've considered adding it as a problem for the tensor2tensor library.

**Comment by YANG-H** [comment]
Hi @daerduoCarey , so the `furthest` is directly measured in euclidean distance, not geodesic distance, right?

BTW, do you still have the record of the mapping between a point cloud and its corresponding off file?

Thank you.

**Comment by charlesq34** [comment]
@YANG-H Yes, it's in Euclidean space.

I think if you go to the data folder there are some TXT files that tell the mapping.

**Comment by yiakwy** [comment]
@godspeed1989 @daerduoCarey  Hi, this data read is of form [B, N, C], where according to implementaiton, B is of size 2048, 1024 for N and 3 for C. How did you say

> How could you generate fixed size(1024,2^10)

I am also curious that is that [N, C] represent a singple pcd file (3d object) or just part of it. Because it is too small. We usually have more than 1000, 000 points for a file. Coud you @daerduoCarey how and why your team used the data with that quantity? Thank you in advance.

**Comment by chengengliu** [comment]
I am wondering the logic behind the scene, why in the PointNet paper they chose to sample 4096 points? Is this choice made due to computational efficiency? Was the number chosen for a reason?
