### ISSUE TITLE
confusion about T-Net.

### ISSUE THREAD

**Issue by wshilin** [charlesq34/pointnet#44]
Hi Charles,
I have some confusion about T-Net:
1.How can the T-Net update its weights in the network.You know,error BackPropagation algorithm need error to update the weights,but I can't find any error about the T-Net.
2.The T-Net's role is ''to align all input set to a canonical space before feature extraction'',you said in your paper,but how can an architecture like T-Net achieves that goal?

**Comment by tokotchd** [comment]
I know I'm not Charles but if you're willing to take my answer, I'll explain the best I can:

Both layers of T-Net are just additional "Layers" on the neural network.  The same Back Propagation algorithm is used to train its weights, even at the same time as the lower parts of the network.  The whole thing is trained on the data at once.

T-Net is a "Spatial Transformer Network" as detailed here: https://arxiv.org/pdf/1506.02025.pdf.  In the case of the "upper" T-Net, the network functions as a way of allowing the neural net to "learn" a set of transformations to align the input to a canonical space before feature extraction.  With 3D point clouds, the 3x3 matrix produced will always be a "tranformation" matrix of some sort.  See https://en.wikipedia.org/wiki/Transformation_matrix for more information.
The lower T-Net in principle is performing the same style of transform, but it aims to align features to a canonical setting in "feature space" instead of geometric space.  It is chosen to be expressed in a 64x64 matrix for the same reasons as the geometric space transform matrix is chosen to be a 3x3 (features are expressed in a 64-tuple instead of a 3-tuple.

Hope this helps.

**Comment by charlesq34** [comment]
Hi @wshilin  I think @tokotchd has made a good explanation on the T-nets.
@tokotchd thanks for the comment!

**Comment by PranjaLBiswas27** [comment]
Hi @charlesq34 @wshilin @tokotchd ,

It might seem very trivial but can someone explain what does it mean by "aligning input to a canonical space by using transformations". Thanks a lot in advance.

Kind Regards
Pranjal Biswas

**Comment by usherbob** [comment]
You may refer to the paper "spatial transform network". @PranjaLBiswas27
