### ISSUE TITLE
Sem Seg: Reason for reducing xyz values by xyz_min in `indoor3d_util` for data preprocessing

### ISSUE THREAD

**Issue by mgooty** [charlesq34/pointnet#50]
Why do we reduce the xyz values by xyz_min during data pre-processing for Semantic Segmentation? The following link points to the lines I am referring to:

https://github.com/charlesq34/pointnet/blob/master/sem_seg/indoor3d_util.py#L52-L62

There is a note in the method which states:

> the points are shifted before save, the most negative point is now at origin.

What does this mean? and Why do we need to do it? Do I need to do the same if I am preparing my own data?

**Comment by charlesq34** [comment]
Hi @mgooty 

The original XYZ are in a global coordinates s.t. all rooms' point cloud are living in the same coordinate system. Since we care more about per-room segmentation, we can change the XYZ from this global coord. to a per-room coordinate system. To achieve that goal, we extract all point XYZ in a room by the xyz_min of them.

**Comment by charlesq34** [comment]
closing due to end of conversation.
