### ISSUE TITLE
The fluctuation of the performance during training

### ISSUE THREAD

**Issue by maggie0106** [charlesq34/pointnet#52]
Hi,
Thanks for sharing your amazing work! I have a quick question. I have trained several trails of the point net on the ModelNet 40 dataset with all the default parameters in the code. I saw quite big performance fluctuation during the training, so it's a bit hard to pinpoint when the model converges. So is there any way to alleviate this performance fluctuation problem? Thanks

Sincerely,
Maggie

**Comment by charlesq34** [comment]
Hi Maggie,

The dataset is quite small (in some categories there are only 100 objects for training and a few for testing) so the result is not stable. What I usually do is to observe the loss curve and "early stop" the training at 200 or 250 epochs.

For stable evaluation I suggest you use the evaluation code which evaluates point cloud in all rotations instead of just the default rotation provided by ModelNet40.

Hope it helps

**Comment by maggie0106** [comment]
Hi Charles,
Thanks for replying me! I will try the method u mentioned.

Cheers,
Maggie
