### ISSUE TITLE
part segmentation

### ISSUE THREAD

**Issue by Loooooper** [charlesq34/pointnet#56]
I just want more information about partial object part segmentation in your article. How could you determine the six viewpoints? Can you provide the partial data in the object part segmentation?

**Comment by charlesq34** [comment]
Hi @Loooooper 

Sorry for the late response. Since there is no quantitative evaluation on the partial scans, we didn't include the data here. You are welcomed to generate your own versions with BlenSor (http://www.guancha.cn/industry-science/2017_11_30_437227_1.shtml)

The six viewpoints are randomly picked with azimuth (rotations around up-axis) angles from Uniform[0,360] and elevation angles from Uniform[-30,30]

Best,
Charles
