### ISSUE TITLE
Semantic segmentation experiments

### ISSUE THREAD

**Issue by Logrus** [charlesq34/pointnet#6]
Hi,

I am currently trying to do experiments on semantic segmentation similar to what is described in the paper.

I took Stanford 3d dataset ([building parser](http://buildingparser.stanford.edu/dataset.html)) and cut it in 1m^3 cubes ([example video of assembling pieces back into the scene](https://youtu.be/oDYDG1NVgK4)). After that I sample 4096 points in each cube.
So now I have (16651x4096x6) array  where 6 is a vector (x,y,z,r,g,b).

However, I find the next step of creating 9-dim vectors for training confusing and would appreciate if you could clarify what is exactly in the 9-dim vector that you have used.
From paper I get it the following way:
1. Original x,y,z in global space
2. Normalized x',y',z' from [0,1] (normalized x,y,z values from above. Or should it be relative to the whole room/scene?)
3. RGB values (they are from 0 to 255 and should be normalized to 0 and 1, right?)

At the same time, just using original x,y,z (potentially huge numbers) and values normalized between 0 and 1 doesn't seem to be correct, because the magnitude of the inputs is likely to affect the training process. Do you normalize them to something like 0 and 1 or from -1 to 1?

I am basically curious about how important RGB information for pointnet. It obviously helps, but it is interesting how much. Have you done or plan to do such experiments?

Best,
Vladislav

**Comment by charlesq34** [comment]
Hi Vladislav,

Original XYZ: we kept Z as it is and shift XY with regard to the center of the block s.t. the center will have X=0, Y=0
Normalized X'Y'Z': it's normalized with regard to the entire room so that the corners will be (0,0,0), (0,1,0) etc.
RGB values: it's converted to 0~1 as float

RGB helps for recognizing objects/regions with special colors, for example wooden tables and black chair legs. If you refer to the paper of the dataset you can see some comparisons of using different combinations of point info.

Hope it helps!

**Comment by Logrus** [comment]
Thanks! It definitely helps.
So Normalized X'Y'Z' is a piece that corresponds to the whole room squashed into the cube where the closest corner is (0,0,0) and the furthest corner is (1,1,1)?

Best,

**Comment by charlesq34** [comment]
Yes, your understanding is correct!

**Comment by Logrus** [comment]
Thanks again! Everything is clear now.
